# ***-specific parameters
underlyings:
  - ROG:SW    # Roche Holding AG
  - ZURN:SW   # Zurich Insurance
  - CH0038863350  # Rothschild & Co bond

maturities: [1d, 1w, 1m, 3m, 6m, 1y] 
moneyness: [0.7, 0.85, 0.95, 1.0, 1.05, 1.15, 1.3]

# Heston calibration bounds (FINMA-compliant)
calibration:
  v0: [0.01, 0.5]      # Initial variance
  theta: [0.01, 0.5]    # Long-term variance
  kappa: [0.1, 10.0]    # Mean reversion
  rho: [-0.95, -0.3]    # Correlation (Swiss equities)
  sigma: [0.1, 2.0]     # Vol-of-vol

# FRTB stress scenarios
stress_scenarios:
  - name: "2020-COVID"
    vix: 85.0
    rate_change: -0.015
  - name: "2011-CHF-Peg"
    fx_shift: 
      EURCHF: -0.15
      
      stress_scenarios:
  - name: "2020-COVID"
    description: "VIX spike to 85, CHF rates drop"
    vix: 85.0
    rate_change: -0.015
    equity_shock: -0.35
    
  - name: "2011-CHF-Peg"
    description: "Swiss National Bank EURCHF floor removal"
    fx_shift: 
      EURCHF: -0.15
    rate_change: -0.0075
    vol_multiplier: 2.5
    
  - name: "Rothschild_Internal_Stress"
    description: "Proprietary scenario for UHNW portfolios"
    liquidity_drain: 0.4
    credit_spread_widening: 0.02